version: "3.8"
services:
  # graph:
  #   container_name: graph
  #   volumes:
  #     - ./graphs:/var/opentripplanner
  #   image: docker.io/opentripplanner/opentripplanner:2.4.0
  #   command: --load --serve
  #   ports:
  #     - 8080:8080

  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass tjredis
    volumes:
      - redis:/data

  app:
    container_name: server
    restart: always
    build: .
    volumes:
      - .:/app
      - ignore:/app/env/
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - redis
      # - graph
    command: sh -c "uvicorn main:app --reload --host 0.0.0.0 --port 8000"

volumes:
  redis:
  ignore:
