version: '3.8'
services:
  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass tjredis
    volumes: 
      - redis:/data
  app:
    container_name: server
    restart: always
    build: .
    volumes:
      - .:/app
      - ignore:/app/env/
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - redis
    command: sh -c "uvicorn main:app --reload --host 0.0.0.0 --port 8000"
volumes:
  redis:
  ignore: